#!/bin/bash
if [[ "$1" == "-h" ]]; then
   # If the 'nginx-centos7' assemble script is executed with '-h' flag,
   # print the usage.
   exec /usr/libexec/s2i/usage
fi

run-postgresql &
sleep 30
pg_ctl -D /var/lib/pgsql/data/userdata stop

cp /tmp/pg_hba.conf /var/lib/pgsql/data/userdata/
cp /tmp/postgresql.conf /var/lib/pgsql/data/userdata/

cat >> ~/.pgpass <<EOF
localhost:5432:*:hummingbird:hummingbird
EOF
chmod 0600 ~/.pgpass

if [ "$(ls -A /tmp/src/backup.tar.gz)" ]; then
     echo "restoring from backup.."
     rm -rf /var/lib/postgresql/9.4/main/*
     mv /tmp/src/backup.tar.gz /var/lib/postgresql/9.4/main/
     cd /var/lib/postgresql/9.4/main/
     gunzip backup.tar.gz
     tar xvf backup.tar 
#     chown -R postgres:postgres /var/lib/postgresql/9.4/main/
     chmod -R 0700 /var/lib/postgresql/9.4/main/
     rm backup.tar
else
    echo "backup is Empty. initializing empty databases for development.."
#     chown -R postgres:postgres /var/lib/postgresql/9.4/main/ /etc/postgresql/9.4/
    #we start up the database server, and run our necessary sql to initialize our empty databases
    pg_ctl start -D /var/lib/pgsql/data/userdata/ &
    sleep 10
#    psql < /tmp/src/sql/postgresql_setup.sql
#    TENANT_DB=$(ls /tmp/src/*.sql.gz | head -n 1 | cut -d "/" -f4 | cut -d "." -f1)
#    if [ -n "$TENANT_DB" ]; then
#	psql -U hummingbird -h localhost -c "create database $TENANT_DB with owner hummingbird";
#        zcat -d /tmp/src/$TENANT_DB.sql.gz | psql -U hummingbird -h localhost -d $TENANT_DB
#    fi
    pg_ctl stop -D /var/lib/pgsql/data/userdata/
fi


#run some SQL on all databases to make sure there isn't a ROOT PIM db that may be pointing to a database other than localhost (like our PIM production database)
#echo "set all tenant configuration to point to 'localhost"
#/usr/lib/postgresql/9.4/bin/pg_ctl start -D /etc/postgresql/9.4/main/
#sleep 10
#psql -U hummingbird -h localhost -c "\l" | grep hummingbird | sed s/" "//g | cut -d "|" -f1 | sed "s,.*,psql -U hummingbird -d & -c \"update hospice set dbhost = 'localhost'\, dbpassword='hummingbird'\","  | bash
#/usr/lib/postgresql/9.4/bin/pg_ctl stop -D /etc/postgresql/9.4/main/
 
