#!/bin/bash

#chown -Rf postgres:postgres /var/lib/postgresql/9.4/main
#chmod -R 700 /var/lib/postgresql/9.4/main
/usr/lib/postgresql/9.4/bin/postgres -D /var/lib/postgresql/9.4/main -c config_file=/etc/postgresql/9.4/main/postgresql.conf
