#!/bin/bash -e
cat <<EOF
this is the image for the main HBEE 'hummingbird' database
To use it, install S2I: https://github.com/openshift/source-to-image
Sample invocation:
s2i build src/  services-hummingbird-database-builder services-hummingbird-database
You can then run the resulting image via:
docker run -it -p 5432:5432 services-hummingbird-database
EOF
